### PR TITLE
fix the bug of backing up a remote host

### PR DESCRIPTION
**Pull request by wang-borong**

### CODE REVIEW

**Comment by jehb** [comment]
Hi @stuha, let me confer with the original author of this script and see if I can get him to review your changes. I'm not sure if he's on GitHub.

**Review by jehb — APPROVED** [review]
The original author reviewed via email. "Most of the changes look like they simply remove a bit of non-printing whitespace on a number of lines. There are two spelling changes to the Help procedure that makes sense as I have previously added them to my own copy of this code. This all looks like some basic cleanup to me so I am definitely fine with it."

**Comment by stuha** [comment]
OK, that's great! Thanks a lot!

**Comment by wang-borong** [comment]
@jehb OK, that's great! Thanks a lot!

**Pull request merged**
